### ISSUE TITLE
Full list?

### ISSUE THREAD

**Issue by mdroidian** [OOlashyn/PowerAppsPortalSiteSettingsAndSnippets#4]
Hey OOlashyn,

These are great!  Thank you.

Is this the full list?
If not, is there a full list somewhere?

And if there isn't, how did you figure these ones out?

Thanks again!

**Comment by OOlashyn** [comment]
Hi @mdroidian,
No this is not the full list. It is a compilation of many snippets known to me and other contributors. We found them by inspecting a code of old adxstudio Portals, reading docs and blog posts.

**Comment by mdroidian** [comment]
Ah, k.  Thank you. 👍
